steps:
  - name: Preconfigure
    image: node
    commands:
      - npm ci

  - name: Build
    image: node
    commands:
      - npm run build

  - name: prepare-deploy
    image: node:20
    commands:
      - mkdir deploy
      - cp -r .next public package.json package-lock.json deploy/
  
  - name: compress
    image: node:20
    commands:
      - tar -czf hackzogtum-webpage.tar.gz deploy/

  - name: Publish
    image: node:20
    commands:
      - mkdir -p ~/.ssh
      - printf '%s' "$${TOKEN_ENV}" > ~/.ssh/id_ed25519
      - chmod 600 ~/.ssh/id_ed25519
      - ssh-keyscan -H 95.217.86.151 >> ~/.ssh/known_hosts
      - ssh -i ~/.ssh/id_ed25519 website@95.217.86.151
    environment:
       TOKEN_ENV:
         from_secret: SSH-Key

when:
  - branch: main