steps:
  - name: Preconfigure
    image: node:20
    commands:
      - npm ci

  - name: Build
    image: node:20
    commands:
      - npm run build
  
  - name: Compress Build Folder
    image: node:20
    commands:
      - tar -czf hackzogtum-webpage.tar.gz --exclude=*.tar.gz .

  - name: Prepare SSH Connection
    image: node:20
    commands:
      - mkdir -p ~/.ssh
      - printf '%s' "$${TOKEN_ENV}" > ~/.ssh/id_ed25519
      - chmod 600 ~/.ssh/id_ed25519
      - ssh-keyscan -H 95.217.86.151 >> ~/.ssh/known_hosts
    environment:
       TOKEN_ENV:
         from_secret: SSH-Key
  
  - name: Publish
    image: node:20
    commands:
      - cat hackzogtum-webpage.tar.gz | ssh -i ~/.ssh/id_ed25519 website@95.217.86.151
    

when:
  - event: push
    branch: main