steps:
  - name: Preconfigure
    image: node
    commands:
      - npm ci
  - name: Build
    image: node
    commands:
      - npm run build

when:
  - event: pull_request
  - event: push
    branch:
      exclude: [main]